import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import customersRouter from "./customers";
import jobsRouter from "./jobs";
import quotesRouter from "./quotes";
import invoicesRouter from "./invoices";
import fleetRouter from "./fleet";
import adminRouter from "./admin";
import leadsRouter from "./leads";
import portalRouter from "./portal";
import accountingRouter from "./accounting";
import aiRouter from "./ai";
import setupRouter from "./setup";
import invitesRouter from "./invites";
import deleteRequestsRouter from "./deleteRequests";
import exportRouter from "./export";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use(dashboardRouter);
router.use(customersRouter);
router.use(jobsRouter);
router.use(quotesRouter);
router.use(invoicesRouter);
router.use(fleetRouter);
router.use(adminRouter);
router.use(leadsRouter);
router.use(accountingRouter);
router.use(aiRouter);
router.use(setupRouter);
router.use(invitesRouter);
router.use(deleteRequestsRouter);
router.use(exportRouter);
router.use("/portal", portalRouter);

export default router;
