// Hand-rolled hooks for endpoints that aren't (yet) generated by Orval.
// These call the same `customFetch` mutator the orval client uses, so
// session cookies / base URL / error handling stay consistent. When
// these endpoints are eventually moved into openapi.yaml the hooks here
// can be replaced with the generated equivalents.

import { useMutation, useQuery } from "@tanstack/react-query";
import { customFetch } from "@workspace/api-client-react";

// ---------- Asset extension fields ----------

// Server includes these on every Asset payload; the orval-generated
// `Asset` type doesn't know about them yet, so we widen at the call
// site via this intersection.
export type AssetExt = {
  category: "TRUCK" | "TRAILER" | "HANDHELD" | "CUSTOM";
  customCategoryLabel: string | null;
  quantity: number;
  assignedCrewId: number | null;
  assignedCrewName: string | null;
  lastAssignedAt: string | null;
  lastAssignedByUserId: number | null;
  lastAssignedByName: string | null;
  // Trailers + quantity-tracked items report `usageUnit: "NONE"` and
  // a sentinel `usageUntilDue` value. UIs gate on usageUnit before
  // formatting the "X miles until due" string.
  usageUnit: "MILES" | "HOURS" | "NONE";
  // Period rollups for the cost-period selector.
  mtdSpendCents: number;
  last30SpendCents: number;
  // Hero image + holder fields (added in the v2 fleet pass).
  hasImage: boolean;
  imageDataUrl: string | null;
  currentHolderUserId: number | null;
  currentHolderName: string | null;
  currentCheckoutId: number | null;
  currentCheckoutSince: string | null;
  lastHolderUserId: number | null;
  lastHolderName: string | null;
  lastCheckedOutAt: string | null;
  // Storage location for equipment (e.g. "Lawn Yard", "Tree Yard").
  // Null for trucks — they move between sites.
  location: string | null;
  // Purchase price in cents — surfaced here so the UI can display and
  // edit it even though the orval-generated Asset type may not include it.
  purchasePriceCents: number | null;
  // Identifier (VIN for trucks, serial for equipment) + spec fields
  // the Edit Asset dialog pre-fills from. All already present in the
  // /assets payload.
  identifier: string | null;
  plate: string | null;
  equipmentType: string | null;
  purchaseDate: string | null;
  serviceIntervalUsage: number;
  currentUsage: number;
  // Insurance schedule fields (trucks/trailers only; null for equipment)
  year: number | null;
  statedValueCents: number | null;
  gvwGcwLbs: number | null;
  garagingState: string | null;
  operatingRadiusMiles: number | null;
  insuranceVehNumber: number | null;
  bodyTypeCode: string | null;
};

// ---------- Asset image ----------
export function useAssetImage(slug: string, enabled = true) {
  return useQuery({
    queryKey: ["asset-image", slug] as const,
    queryFn: () =>
      customFetch<{ imageDataUrl: string | null }>(
        `/api/assets/${encodeURIComponent(slug)}/image`,
      ),
    enabled: enabled && slug.length > 0,
  });
}

export function useUpdateAssetImage(slug: string) {
  return useMutation({
    mutationFn: (imageDataUrl: string | null) =>
      customFetch<{ ok: boolean; hasImage: boolean }>(
        `/api/assets/${encodeURIComponent(slug)}/image`,
        {
          method: "PUT",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ imageDataUrl }),
        },
      ),
  });
}

// ---------- Asset checkout / check-in ----------
export type AssetCheckout = {
  id: number;
  userId: number;
  userName: string | null;
  checkedOutByUserId: number | null;
  checkedOutByName: string | null;
  checkedOutAt: string;
  checkedInAt: string | null;
  checkedInByUserId: number | null;
  checkedInByName: string | null;
  notes: string | null;
};

export function useCheckoutHistory(slug: string) {
  return useQuery({
    queryKey: ["asset-checkouts", slug] as const,
    queryFn: () =>
      customFetch<{ history: AssetCheckout[] }>(
        `/api/assets/${encodeURIComponent(slug)}/checkouts`,
      ),
    enabled: slug.length > 0,
  });
}

export function useCheckOutAsset(slug: string) {
  return useMutation({
    mutationFn: (body: { userId: number; notes?: string | null }) =>
      customFetch<{ checkout: { id: number } }>(
        `/api/assets/${encodeURIComponent(slug)}/checkout`,
        {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify(body),
        },
      ),
  });
}

export function useCheckInAsset(slug: string) {
  return useMutation({
    mutationFn: (body: { notes?: string | null }) =>
      customFetch<{ checkout: { id: number } }>(
        `/api/assets/${encodeURIComponent(slug)}/checkin`,
        {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify(body),
        },
      ),
  });
}

// ---------- Crews ----------
// `Crew` is the list-summary shape from GET /crews. The counts +
// lead/department fields power the at-a-glance grid on the Crews page;
// the older `{ id, name }` consumers (dropdowns, asset assignment) keep
// working since they only read those two fields.
export type Crew = {
  id: number;
  name: string;
  leadUserId?: number | null;
  leadName?: string | null;
  departmentId?: number | null;
  departmentLabel?: string | null;
  memberCount?: number;
  truckCount?: number;
  equipmentCount?: number;
};
export type CrewMember = {
  userId: number;
  fullName: string;
  role: string;
  department: string;
};
export type CrewDetail = {
  id: number;
  name: string;
  leadUserId: number;
  departmentId: number | null;
  members: CrewMember[];
  trucks: Array<{ id: number; name: string; status: string; slug: string | null }>;
  equipment: Array<{ id: number; name: string; type: string; status: string; slug: string | null }>;
};

const CREWS_KEY = ["crews"] as const;

export function useListCrews() {
  return useQuery({
    queryKey: CREWS_KEY,
    queryFn: () => customFetch<{ crews: Crew[] }>("/api/crews"),
  });
}

export function getCrewDetailKey(id: number) {
  return ["crew", id] as const;
}

export function useCrewDetail(id: number) {
  return useQuery({
    queryKey: getCrewDetailKey(id),
    queryFn: () => customFetch<{ crew: CrewDetail }>(`/api/crews/${id}`),
    enabled: id > 0,
  });
}

// ---------- Equipment Items ----------
export type EquipmentItem = {
  id: number;
  equipmentId: number;
  name: string;
  quantity: number;
  unit: string | null;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
};

export function getEquipmentItemsKey(equipmentId: number) {
  return ["equipment-items", equipmentId] as const;
}

export function useEquipmentItems(equipmentId: number) {
  return useQuery({
    queryKey: getEquipmentItemsKey(equipmentId),
    queryFn: () =>
      customFetch<{ items: EquipmentItem[] }>(`/api/equipment/${equipmentId}/items`),
    enabled: equipmentId > 0,
  });
}

export type CreateEquipmentItemBody = {
  name: string;
  quantity?: number;
  unit?: string;
  notes?: string;
};

export function useCreateEquipmentItem(equipmentId: number) {
  return useMutation({
    mutationFn: (body: CreateEquipmentItemBody) =>
      customFetch<{ item: EquipmentItem }>(`/api/equipment/${equipmentId}/items`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
      }),
  });
}

export function useDeleteEquipmentItem(equipmentId: number) {
  return useMutation({
    mutationFn: (itemId: number) =>
      customFetch<{ ok: boolean }>(`/api/equipment/${equipmentId}/items/${itemId}`, {
        method: "DELETE",
      }),
  });
}

export type UpdateEquipmentItemBody = {
  name?: string;
  quantity?: number;
  unit?: string | null;
  notes?: string | null;
};

export function useUpdateEquipmentItem(equipmentId: number) {
  return useMutation({
    mutationFn: ({ itemId, data }: { itemId: number; data: UpdateEquipmentItemBody }) =>
      customFetch<{ item: EquipmentItem }>(`/api/equipment/${equipmentId}/items/${itemId}`, {
        method: "PATCH",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(data),
      }),
  });
}

// ---------- Assignment ----------
export type AssignAssetBody = { crewId: number | null; note?: string };

export function useAssignAsset(slug: string) {
  return useMutation({
    mutationFn: (body: AssignAssetBody) =>
      customFetch<{ asset: unknown }>(`/api/assets/${encodeURIComponent(slug)}/assign`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
      }),
  });
}

export type AssignmentHistoryEntry = {
  id: number;
  changedAt: string;
  oldCrewId: number | null;
  oldCrewName: string | null;
  newCrewId: number | null;
  newCrewName: string | null;
  changedByUserId: number | null;
  changedByName: string | null;
  note: string | null;
};

export function getAssignmentHistoryKey(slug: string) {
  return ["assignment-history", slug] as const;
}

export function useAssignmentHistory(slug: string) {
  return useQuery({
    queryKey: getAssignmentHistoryKey(slug),
    queryFn: () =>
      customFetch<{ history: AssignmentHistoryEntry[] }>(
        `/api/assets/${encodeURIComponent(slug)}/assignment-history`,
      ),
  });
}

// ---------- Create Truck ----------
export type CreateTruckBody = {
  name: string;
  vehicleType?: "TRUCK" | "TRAILER";
  brand?: string;
  model?: string;
  vin?: string;
  plate?: string;
  status?: string;
  departmentId: number;
  purchasePriceCents?: number;
  purchaseDate?: string;
  currentMileage?: number;
  serviceIntervalMiles?: number;
};

export function useCreateTruck() {
  return useMutation({
    mutationFn: (body: CreateTruckBody) =>
      customFetch<{ truck: unknown }>("/api/trucks", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ ...body, status: body.status ?? "ACTIVE" }),
      }),
  });
}

// ---------- Create Equipment ----------
export type CreateEquipmentBody = {
  name: string;
  type: string;
  category?: "HANDHELD" | "CUSTOM";
  customCategoryLabel?: string;
  quantity?: number;
  brand?: string;
  model?: string;
  serial?: string;
  status?: string;
  departmentId: number;
  purchasePriceCents?: number;
  purchaseDate?: string;
  currentHours?: number;
  serviceIntervalHours?: number;
};

export function useCreateEquipment() {
  return useMutation({
    mutationFn: (body: CreateEquipmentBody) =>
      customFetch<{ equipment: unknown }>("/api/equipment", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ ...body, status: body.status ?? "ACTIVE" }),
      }),
  });
}

// ---------- Update Truck / Equipment (full field set) ----------
// The orval-generated useUpdateTruck / useUpdateEquipment hooks only know
// the fields in openapi.yaml. These hand-rolled variants send the full
// column set the server's PATCH handlers accept (vehicleType, category,
// quantity, location, insurance-schedule fields, …). Every key is
// optional: PATCH semantics on the server mean omitted keys are left
// untouched and `null` explicitly clears a nullable column.
export type UpdateTruckExtBody = {
  name?: string;
  vehicleType?: "TRUCK" | "TRAILER";
  brand?: string | null;
  model?: string | null;
  vin?: string | null;
  plate?: string | null;
  status?: "ACTIVE" | "IN_SHOP" | "RETIRED";
  assignedCrewId?: number | null;
  departmentId?: number | null;
  purchasePriceCents?: number | null;
  purchaseDate?: string | null;
  currentMileage?: number;
  serviceIntervalMiles?: number;
  year?: number | null;
  statedValueCents?: number | null;
  gvwGcwLbs?: number | null;
  garagingState?: string | null;
  operatingRadiusMiles?: number | null;
  insuranceVehNumber?: number | null;
  bodyTypeCode?: string | null;
};

export function useUpdateTruckExt() {
  return useMutation({
    mutationFn: ({ id, data }: { id: number; data: UpdateTruckExtBody }) =>
      customFetch<{ truck: unknown }>(`/api/trucks/${id}`, {
        method: "PATCH",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(data),
      }),
  });
}

export type UpdateEquipmentExtBody = {
  name?: string;
  type?: string;
  category?: "HANDHELD" | "CUSTOM";
  customCategoryLabel?: string | null;
  quantity?: number;
  brand?: string | null;
  model?: string | null;
  serial?: string | null;
  location?: string | null;
  status?: "ACTIVE" | "IN_SHOP" | "RETIRED";
  assignedTruckId?: number | null;
  departmentId?: number | null;
  purchasePriceCents?: number | null;
  purchaseDate?: string | null;
  currentHours?: number;
  serviceIntervalHours?: number;
};

export function useUpdateEquipmentExt() {
  return useMutation({
    mutationFn: ({ id, data }: { id: number; data: UpdateEquipmentExtBody }) =>
      customFetch<{ equipment: unknown }>(`/api/equipment/${id}`, {
        method: "PATCH",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(data),
      }),
  });
}

// ---------- Usage reading corrections ----------
export type UsageReading = {
  id: number;
  truckId: number | null;
  equipmentId: number | null;
  mileage: number | null;
  hours: number | null;
  recordedAt: string;
  recordedByUserId: number | null;
  notes: string | null;
};

export type UpdateUsageReadingBody = {
  mileage?: number;
  hours?: number;
  recordedAt?: string;
  notes?: string | null;
};

export function useUpdateUsageReading() {
  return useMutation({
    mutationFn: ({ id, data }: { id: number; data: UpdateUsageReadingBody }) =>
      customFetch<{ reading: UsageReading }>(`/api/usage-readings/${id}`, {
        method: "PATCH",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(data),
      }),
  });
}

export function useDeleteUsageReading() {
  return useMutation({
    mutationFn: (id: number) =>
      customFetch<{ ok: boolean }>(`/api/usage-readings/${id}`, {
        method: "DELETE",
      }),
  });
}

// ---------- Crew Lead Candidates ----------
// Fleet-view-gated endpoint that returns a minimal user list for the
// crew-lead selector in the New Crew dialog. Works for MECHANIC role.
export type CrewLeadCandidate = { id: number; fullName: string };

export function useListCrewLeadCandidates() {
  return useQuery({
    queryKey: ["crew-lead-candidates"] as const,
    queryFn: () => customFetch<{ users: CrewLeadCandidate[] }>("/api/crews/lead-candidates"),
  });
}

// ---------- Create Crew ----------
export type CreateCrewBody = {
  name: string;
  leadUserId: number;
  departmentId?: number;
};

export function useCreateCrew() {
  return useMutation({
    mutationFn: (body: CreateCrewBody) =>
      customFetch<{ crew: { id: number; name: string } }>("/api/crews", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
      }),
  });
}

// ---------- Update Crew (re-point lead, rename, etc.) ----------
export type UpdateCrewBody = {
  name?: string;
  leadUserId?: number;
  departmentId?: number | null;
};

export function useUpdateCrew(crewId: number) {
  return useMutation({
    mutationFn: (body: UpdateCrewBody) =>
      customFetch<{
        crew: {
          id: number;
          name: string;
          leadUserId: number;
          departmentId: number | null;
        };
      }>(`/api/crews/${crewId}`, {
        method: "PATCH",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
      }),
  });
}

export function useDeleteCrew() {
  return useMutation({
    mutationFn: (crewId: number) =>
      customFetch<{ ok: boolean }>(`/api/crews/${crewId}`, {
        method: "DELETE",
      }),
  });
}

// ---------- Maintenance Receipt ----------
// Side endpoint that lets the maintenance dialog attach a vendor
// receipt photo (base64 data URL) and accountant-facing fields
// without polluting the orval-generated maintenance log create/update
// shapes.
export type MaintenanceReceiptCategory =
  | "LABOR"
  | "PARTS"
  | "FUEL"
  | "OUTSOURCED"
  | "OTHER";

export type UpdateReceiptBody = {
  vendor?: string | null;
  category?: MaintenanceReceiptCategory | null;
  notes?: string | null;
  receiptDataUrl?: string | null;
};

export function useUpdateMaintenanceReceipt(logId: number) {
  return useMutation({
    mutationFn: (body: UpdateReceiptBody) =>
      customFetch<{
        log: {
          id: number;
          vendor: string | null;
          category: string | null;
          notes: string | null;
          hasReceipt: boolean;
        };
      }>(`/api/maintenance-logs/${logId}/receipt`, {
        method: "PUT",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
      }),
  });
}

// ---------- Delete-request approval queue ----------

export type DeleteRequest = {
  id: number;
  requestedByUserId: number;
  requestedByName: string | null;
  requestedByEmail: string | null;
  resourceKind: string;
  resourceId: number;
  resourceLabel: string | null;
  reason: string | null;
  status: "EXECUTED" | "PENDING" | "APPROVED" | "DENIED";
  createdAt: string;
  decidedAt: string | null;
  decidedByUserId: number | null;
  decidedByName: string | null;
};

export const DELETE_REQUESTS_KEY = ["delete-requests"] as const;
export const DELETE_REQUESTS_PENDING_COUNT_KEY = [
  "delete-requests",
  "pending-count",
] as const;

export function useListDeleteRequests() {
  return useQuery({
    queryKey: DELETE_REQUESTS_KEY,
    queryFn: () =>
      customFetch<{ requests: DeleteRequest[] }>("/api/delete-requests"),
  });
}

export function usePendingDeleteRequestCount() {
  return useQuery({
    queryKey: DELETE_REQUESTS_PENDING_COUNT_KEY,
    queryFn: () =>
      customFetch<{ count: number }>("/api/delete-requests/pending-count"),
    // Refresh on a slow interval so the sidebar badge feels live
    // without hammering the server.
    refetchInterval: 60_000,
    refetchOnWindowFocus: true,
  });
}

export function useApproveDeleteRequest() {
  return useMutation({
    mutationFn: (id: number) =>
      customFetch<{ ok: true }>(`/api/delete-requests/${id}/approve`, {
        method: "POST",
      }),
  });
}

export function useDenyDeleteRequest() {
  return useMutation({
    mutationFn: (id: number) =>
      customFetch<{ ok: true }>(`/api/delete-requests/${id}/deny`, {
        method: "POST",
      }),
  });
}

// ---------- Setup + Invites ----------

export const NEEDS_SETUP_KEY = ["setup", "needs-setup"] as const;

export function useNeedsSetup() {
  return useQuery({
    queryKey: NEEDS_SETUP_KEY,
    queryFn: () => customFetch<{ needsSetup: boolean }>("/api/setup/needs-setup"),
    // Refetch only when invalidated; the answer rarely flips.
    staleTime: Infinity,
    refetchOnWindowFocus: false,
  });
}

export type FounderSetupBody = {
  fullName: string;
  email: string;
  password: string;
};

export function useSetupFounder() {
  return useMutation({
    mutationFn: (body: FounderSetupBody) =>
      customFetch<{ user: unknown }>("/api/setup/founder", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
      }),
  });
}

export type Invite = {
  id: number;
  token: string;
  email: string;
  fullName: string | null;
  roleId: number;
  roleKey: string | null;
  departmentId: number;
  departmentKey: string | null;
  departmentLabel: string | null;
  createdByUserId: number | null;
  createdByName: string | null;
  createdAt: string;
  expiresAt: string;
  revokedAt: string | null;
  acceptedAt: string | null;
  acceptedByUserId: number | null;
  status: "pending" | "accepted" | "revoked" | "expired";
};

export type InviteLookup = Omit<Invite, "token">;

export const INVITES_KEY = ["invites"] as const;

export function useListInvites() {
  return useQuery({
    queryKey: INVITES_KEY,
    queryFn: () => customFetch<{ invites: Invite[] }>("/api/invites"),
  });
}

export type CreateInviteBody = {
  email: string;
  fullName?: string;
  roleKey: string;
  // Optional for ADMIN role — the server lands new admins in the
  // synthetic "Admin" home department when departmentId is omitted.
  // All other roles still need an explicit department.
  departmentId?: number;
  expiresInDays?: number;
};

export function useCreateInvite() {
  return useMutation({
    mutationFn: (body: CreateInviteBody) =>
      customFetch<{ invite: Invite }>("/api/invites", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
      }),
  });
}

export function useRevokeInvite() {
  return useMutation({
    mutationFn: (id: number) =>
      customFetch<{ ok: true }>(`/api/invites/${id}/revoke`, {
        method: "POST",
      }),
  });
}

export function useInviteLookup(token: string) {
  return useQuery({
    queryKey: ["invite-lookup", token] as const,
    queryFn: () =>
      customFetch<{ invite: InviteLookup }>(
        `/api/invites/lookup/${encodeURIComponent(token)}`,
      ),
    enabled: token.length > 0,
    retry: false,
  });
}

export type AcceptInviteBody = {
  fullName: string;
  email?: string;
  password: string;
};

export function useAcceptInvite(token: string) {
  return useMutation({
    mutationFn: (body: AcceptInviteBody) =>
      customFetch<{ user: unknown }>(
        `/api/invites/${encodeURIComponent(token)}/accept`,
        {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify(body),
        },
      ),
  });
}

// ---------- AI Assistant ----------
export type AssistantChatMessage = {
  role: "user" | "assistant";
  content: string;
};


export function useMaintenanceReceipt(logId: number, enabled = true) {
  return useQuery({
    queryKey: ["maintenance-receipt", logId] as const,
    queryFn: () =>
      customFetch<{ receiptDataUrl: string | null }>(
        `/api/maintenance-logs/${logId}/receipt`,
      ),
    enabled: enabled && logId > 0,
  });
}

// ---------- Accounting ----------
export type AccountingMonthRow = {
  month: string;
  collectedRevenueCents: number;
  maintenanceSpendCents: number;
};

export type AccountingAging = {
  currentCents: number;
  d1to30Cents: number;
  d31to60Cents: number;
  d61to90Cents: number;
  d90plusCents: number;
};

export type AccountingExpenseCategoryKey =
  | "LABOR"
  | "PARTS"
  | "FUEL"
  | "OUTSOURCED"
  | "OTHER"
  | "UNCATEGORIZED";

export type AccountingExpensesByCategory = Record<
  AccountingExpenseCategoryKey,
  { count: number; cents: number }
>;

export type AccountingQuotesByStatus = {
  draft: { count: number; cents: number };
  sent: { count: number; cents: number };
  approved: { count: number; cents: number };
};

export type AccountingBranch = {
  departmentId: number | null;
  departmentLabel: string;
  openInvoiceCents: number;
  collectedRevenueCents: number;
  quotePipelineCents: number;
  maintenanceSpendCents: number;
  monthly: AccountingMonthRow[];
  aging: AccountingAging;
  expensesByCategory: AccountingExpensesByCategory;
  quotesByStatus: AccountingQuotesByStatus;
  maintenanceLogCount: number;
  maintenanceLogsWithReceipt: number;
};

export type AccountingTopVendor = {
  vendor: string;
  cents: number;
  logCount: number;
};

export type AssetCategoryKey = "TRUCK" | "TRAILER" | "HANDHELD" | "CUSTOM";

export type AccountingAssetSpend = {
  kind: "TRUCK" | "EQUIPMENT";
  assetCategory: AssetCategoryKey;
  customCategoryLabel: string | null;
  id: number;
  slug: string | null;
  name: string;
  status: string;
  departmentId: number | null;
  departmentLabel: string;
  purchasePriceCents: number;
  lifeToDateSpendCents: number;
  ytdSpendCents: number;
  last30DaysSpendCents: number;
  logCount: number;
  logsWithReceipt: number;
};

export type AccountingAssetTypeRollup = Record<
  AssetCategoryKey,
  {
    count: number;
    lifeToDateSpendCents: number;
    ytdSpendCents: number;
    last30DaysSpendCents: number;
    logCount: number;
    logsWithReceipt: number;
    purchasePriceCents: number;
  }
>;

export type AccountingDeptAssetMatrixRow = {
  departmentId: number | null;
  departmentLabel: string;
  cells: Record<AssetCategoryKey, { count: number; cents: number }>;
  totalCents: number;
};

export type AccountingSummary = {
  totals: {
    openInvoiceCents: number;
    collectedRevenueCents: number;
    quotePipelineCents: number;
    maintenanceSpendCents: number;
  };
  branches: AccountingBranch[];
  orgMonthly: AccountingMonthRow[];
  topVendors: AccountingTopVendor[];
  assetSpend: AccountingAssetSpend[];
  assetTypeRollup: AccountingAssetTypeRollup;
  deptAssetMatrix: AccountingDeptAssetMatrixRow[];
};

export const ACCOUNTING_KEY = ["accounting", "summary"] as const;

export function useAccountingSummary() {
  return useQuery({
    queryKey: ACCOUNTING_KEY,
    queryFn: () => customFetch<AccountingSummary>("/api/accounting/summary"),
  });
}

